#!/bin/sh
dart pub get
dart compile exe bin/pkg.dart -o dap
mkdir appimage
cp -r dap appimage/dap
cp -r dahliaOS/* appimage/
chmod +x appimage/dap
ARCH=x86_64 appimagetool appimage/
mv dap-x86_64.AppImage io.dahliaos.dap.dap